si_system: disable for iOS
Autoconf detects that the system function is present but compilation
fails with

error: 'system' is unavailable: not available on iOS

Therefore we manually disable this function for iOS.

Closes #691.